// GAS-editable test configuration.
// Modify this file in Apps Script (testConfig.gs) to turn suites/tests on or off.
var TEST_CONFIG = {
  defaultSuiteEnabled: false,
  unlistedTestsEnabled: false,
  suites: {
    EventManager: {
      enabled: false,
      tests: {
        test_get_event_by_title: false,
        test_getEventList: false,
        test_get_event_by_id: false,
        test_getUpcomingEvents: false,
        test_getUpcomingClasses: false,
        test_getAvailableEvents: false,
        test_when_event_item_exists__then_only_calendar_event_is_added: false,
        test_addEvent: false,
        test_add_recurring_Event: false,
        test_add_event_item: false,
        test_delete_event_item: false,
        test_updateEvent: false,
        test_deleteEvent: false,
        test_when_member_signs_up_for_event__then_event_is_updated: false,
        test_when_member_signs_up_for_recurring_event__then_event_is_updated: false,
        test_getEventRooms: false,
        test_get_calendar_resources: false,
        test_failed_event_update: false,
        test_unregister_member_from_event: false,
        test_when_calendar_manager_is_created__then_configuration_is_correct: false,
        test_when_rooms_are_retrieved__then_at_least_one_room_is_returned: false,
        test_get_event_items: false,
        test_pagination_on_event_items: false,
        test_get_event_rooms__returns_rooms: false,
        test_get_event_rooms__returns_rooms_with_details: false,
        test_get_event_rooms__returns_rooms_with_capacity: false,
      },
    },
    Form: {
      enabled: false,
      tests: {
        test_when_waiverFormSubmitted_then_documentGenerated: false,
        test_when_waiver_is_created_then_waiver_is_available: false,
        test_when_form_is_retrieved__then_it_is_valid: false,
      },
    },
    InvoiceManager: {
      enabled: false,
      tests: {
        test_when_invoice_list_is_requested_then_invoices_exist: false,
        test_when_invoice_is_requested_by_id_then_invoice_exists: false,
        test_when_invoice_is_created_then_invoice_exists: false,
        test_when_invoice_is_created_then_invoice_exists_for_customer: false,
        test_memberRegisters_then_invoice_exists_for_customer: false,
        test_when_invoice_is_created_and_sent__then_invoice_is_received: false,
      },
    },
    Membership: {
      enabled: false,
      tests: {
        test_if_member_registers__then_member_data_is_complete: false,
        test_if_system_sends_email_then_user_receives_email: false,
        test_if_member_is_added_member_is_found: false,
        test_if_duplicate_member_is_not_added: false,
        test_if_registration_form_ignores_missing_fields: false,
        test_when_user_logs_in__then_user_status_is_VERIFYING: false,
        test_when_existing_user_logs_in__then_user_status_is_VERIFYING: false,
        test_verifyToken_transitions_user_to_VERIFIED: false,
        test_getAllMembers_returns_members: false,
        test_getAllMembers_by_page_returns_members: false,
        test_when_a_page_is_requested__then_page_token_is_returned_legacy: false,
        test_whenAuthenticationIsRequested_thenAuthenticationIsVerified: false,
        test_whenFilterIsApplied_thenFilteredDataReturns: false,
        test_whenMemberIsUpdated_thenMemberData_is_changed: false,
        test_whenMemberIsCreatedFromData_thenAllFieldsAreThere: false,
        test_getHosts_returns_hosts: false,
        test_StorageManager_add: false,
        test_StorageManager_getAll: false,
        test_EventManagerGetsAllEvents: false,
        test_EventManagerGetsFilteredEvents: false,
        test_when_get_config__then_key_parameters_are_set: false,
        test_whenStatusFilterIsApplied_thenOnlyMembersWithThatStatusAreReturned: false,
      },
    },
    VendorManager: {
      enabled: false,
      tests: {
        test_when_listInstructors_is_called__then_instructors_are_returned: false,
        test_when_vendor_is_added__then_it_is_valid: false,
      },
    },
    Zoho: {
      enabled: false,
      tests: {
        test_getAllMembers: false,
        test_when_entities_are_retrieved_by_page__then_a_pageSize_list_is_returned: false,
        test_getMemberById: false,
        test_findMemberByEmail: false,
        test_getAllEvents: false,
        test_getEventById: false,
        test_findEventByName: false,
        test_when_contact_is_added__then_it_is_valid: false,
      },
    },
  },
};
